-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6aTSZwW4NXRkQngS
xuiAdEsLbfADC1Y0ku+iNII8pzegCgYIKoZIzj0DAQehRANCAARL45oplpvoyFKa
TiuO9XT+Bh9dMQEjAXc4gD2JdSnzou4gTXq8VAn/kTJymV54lhH2B+dtVb+MX+BR
eElN/8yi
-----END PRIVATE KEY-----